### PR TITLE
Hash Routing and React 15 issue fix

### PR DESCRIPTION
**Pull request by BlakeRxxk**
fix Warning: Unknown prop with _, _query and hash in 0.36.0 and react
in version 15.3.2

ref https://github.com/STRML/react-router-component/issues/178

### CODE REVIEW

**Comment by STRML** [comment]
I don't think this is #178 - you have specifically removed `_query` on the `<Link>` element, but `<Link>` should never be receiving it.

**Comment by BlakeRxxk** [comment]
right, `_query` isn't part of #178 issue, but I've noticed react warning in tests

**Comment by nilsml** [comment]
Is this fix being merged in? Still receiving the warning `Unknown prop 'hash' on <div> tag` when using 0.36.4.

**Comment by BlakeRxxk** [comment]
I can resolve conflict, but need approval of @STRML

**Comment by STRML** [comment]
@nilsml This won't fix the unknown prop `hash` error.

@BlakeRxxk I am still not sure what this fixes. `_query` should never be received by `<Link>`.

**Comment by BlakeRxxk** [comment]
@STRML as i mentioned before - running tests throws ``Unknown prop _query ...`` so i decided to add small fix.

otherwise without ``_query`` fixes it still remove ``Unknown prop 'hash' on <div> tag`` error

**Comment by STRML** [comment]
Aha. I had forgotten we introspect propTypes for the omit lists.

I've adapted this in 65009440c0b0ea79f4aec6111f652d3a8bf9dc58 and will release shortly. Thanks @BlakeRxxk.

**Pull request closed without merging**
