### PR TITLE
Added link to react-async repo

### PR DESCRIPTION
**Pull request by srph**

### CODE REVIEW

**Comment by STRML** [comment]
View the rendered markdown - this may be a little known feature but the link is there.

**Comment by srph** [comment]
You're right. It is there, but just that the [andreypopp.viewdocs.io/react-async](http://andreypopp.viewdocs.io/react-async) does not exist. Might as well link it to the repository itself? :smile:

**Comment by STRML** [comment]
Ah that is a good point. Well, could you please just update the link at the bottom of the file instead?

**Comment by andreypopp** [comment]
The master branch of react async now contains a totally different
implementation.

**Comment by srph** [comment]
@andreypopp Ah I see. To which tag / branch do you suggest should I link it to?

**Comment by STRML** [comment]
We've removed react-async from RRC.

**Pull request closed without merging**
