### PR TITLE
Fix queries

### PR DESCRIPTION
**Pull request by jsg2021**
This PR fixes two issues I found recently around query strings.

#198 & #197

### CODE REVIEW

**Comment by josalmi** [comment]
Any updates on this? Is anyone maintaining this repository anymore?

**Comment by STRML** [comment]
Cycling close/open to nudge Travis.

**Comment by STRML** [comment]
This is failing the build and doesn't have any additional tests to catch the issue. Investigating.

**Comment by STRML** [comment]
Fixed in 85c8030c528f19f8ca99198f4343b3c253968c2f

**Pull request closed without merging**
